### ISSUE TITLE
Cant start the application

### ISSUE THREAD

**Issue by blavejr** [cosmosregistry/chain-minimal#123]
Hi guys I have tried and tried but I am unable to get this application to start

make init doesn't work and throws some errors

```
make init
./scripts/init.sh
rm: /Users/username/.minid: No such file or directory
./scripts/init.sh: line 6: config: command not found
./scripts/init.sh: line 7: config: command not found
./scripts/init.sh: line 8: keys: command not found
./scripts/init.sh: line 9: keys: command not found
./scripts/init.sh: line 10: init: command not found
./scripts/init.sh: line 12: genesis: command not found
./scripts/init.sh: line 13: genesis: command not found
./scripts/init.sh: line 15: genesis: command not found
./scripts/init.sh: line 16: genesis: command not found
make: *** [init] Error 127
```

If there are extra steps please let me know

**Comment by julienrbrt** [comment]
Could you please show what returns:

> $ minid

**Comment by blavejr** [comment]
Hi @julienrbrt it was not found, but I created a PR which I think might fix my issue maybe take a look there.

**Comment by murat1999** [comment]
For those who are wondering how to fix it. 

1. Find the location where minid is installed. It can be in either of this directories: `ls /usr/local/bin/minid` or `ls ~/go/bin/minid`. I found in here `ls ~/go/bin/minid`
2. Edit Your Shell Profile. In my case it was  ~/.zshrc `open -a TextEdit ~/.zshrc`
3. Add to PATH: `export PATH=$PATH:/Users/username/go/bin` add this to the end of file.
4. Apply the changes: `source ~/.zshrc`
5. To verify that `minid` is now correctly in your path, you can run: `which minid`

**Comment by ahmadSaeedGoda** [comment]
I have `minid` command not found, running on Ubuntu 22.04 using zsh.

Having the same issue, what can I do?

**Comment by julienrbrt** [comment]
You need to add $GOBIN to your $PATH.

**Comment by ahmadSaeedGoda** [comment]
Well, I just removed the 3rd line from `go.mod` file:
`toolchain go1.21.0`

and then it worked like a charm!

Kindly lemme know what do you think about that?!

As I believe that basically the issue was coming from not being able to verify that file using the command: `@go mod verify` from the Makefile when running `make install`.

BTW, I am using `gvm` as a version manager for the GoLang installation.

One more thing you may kindly help me with, What can I do after having a successful installation and starting the chain via `minid start`? :grinning: :grin: :100:

**Comment by ahmadSaeedGoda** [comment]
Please excuse my newbie lack of knowledge, I was just expecting the `README` file to expose more info :smile_cat: and guide me through the journey or refer tom some guidance.

**Comment by ahmadSaeedGoda** [comment]
@julienrbrt May you kindly let me know your thoughts :pray:
